---
deployment:
  tasks:
    - export DEPLOYPATH=/public_html
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp about.php $DEPLOYPATH
    - /bin/cp books.php $DEPLOYPATH
    - /bin/cp contact.php $DEPLOYPATH
    - /bin/cp ministries.php $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH